name: Continuous Deployment
#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
on:
  push:
    branches:
      - fix/cd
jobs:
  build-py37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Py37 Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.7.16 3.7
      - name: cache-wheel
        uses: actions/upload-artifact@v2
        with:
          name: py37_wheel
          path: dist/wheelhouse/*-manylinux*.whl
  deploy:
    runs-on: ubuntu-latest
    needs: build-py37
    steps:
      - name: start_deploying
        uses: actions/checkout@v2
      - name: load_wheel_py37
        uses: actions/download-artifact@v2
        with: 
          name: py37_wheel
      - name: Install Twine
        run: |
          pip install twine
          pip install pexpect
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          python -m twine upload dist/wheelhouse/*-manylinux*.whl
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Py37 Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.7.16 3.7
      - name: Build Py38 Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.8.16 3.8
      - name: Build Py39 Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.9.16 3.9
      - name: Build Py310 Wheel
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.10.10 3.10
      - name: Install Twine
        run: |
          pip install twine
          pip install pexpect
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          python -m twine upload dist/wheelhouse/*-manylinux*.whl