name: Continuous Deployment
on: push
#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
jobs:
  build-linux-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-arg: ['3.7.16 3.7', '3.8.16 3.8', '3.9.16 3.9', '3.10.10 3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Build 
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh ${{ matrix.py-arg }}
      - name: Cache
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.py-arg }} wheel
          path: dist/wheelhouse/*-manylinux*.whl
  build-macos-m1-wheel:
    name: Build wheels on macos-11
    runs-on: macos-11
    strategy:
      matrix:
        py-arg: ['cp37', 'cp38', 'cp39', 'cp310']
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_ARCHS_MACOS: x86_64 #arm64
          CIBW_BUILD: ${{ matrix.py-arg }}-macosx_x86_64
      - name: Cache
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.py-arg }}-macosx_x86_64
          path: dist/wheelhouse/*.whl
  deploy:
    runs-on: ubuntu-latest
    needs: [build-linux-wheels, build-macos-m1-wheel]
    steps:
      - name: start deploying
        uses: actions/checkout@v2
      - name: load py37 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.7.16 3.7 wheel
      - name: load py38 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.8.16 3.8 wheel
      - name: load py39 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.9.16 3.9 wheel
      - name: load py310 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.10.10 3.10 wheel
      - name: load cp37-macosx_x86_64
        uses: actions/download-artifact@v2
        with:
          name: cp37-macosx_x86_64
      - name: load cp38-macosx_x86_64
        uses: actions/download-artifact@v2
        with:
          name: cp38-macosx_x86_64
      - name: load cp39-macosx_x86_64
        uses: actions/download-artifact@v2
        with:
          name: cp39-macosx_x86_64
      - name: load cp310-macosx_x86_64
        uses: actions/download-artifact@v2
        with:
          name: cp310-macosx_x86_64
      - name: move wheel
        run: | 
         mkdir dist
         mv *.whl dist/
         ls
         ls dist
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          pip install twine
          pip install pexpect
          python -m twine upload dist/*-manylinux*.whl