name: Publish Python distributions to PyPI
on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install twine
          pip install pexpect
          pip install build --upgrade
      - name: Build
        run: |
          python -m build
      - name: Deploy to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          twine upload dist/* --verbose