name: Continuous Deployment
on: push
#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
jobs:
  build-linux-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-arg: ['3.7.16 3.7', '3.8.16 3.8', '3.9.16 3.9', '3.10.10 3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Build 
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh ${{ matrix.py-arg }}
      - name: Cache
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.py-arg }} wheel
          path: dist/wheelhouse/*-manylinux*.whl
  build-macos-m1-wheel:
    name: Build wheels on macos-11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_ARCHS_MACOS: x86_64
      - name: Cache
        uses: actions/upload-artifact@v3
        with:
          name: macos m1 wheel
          path: dist/wheelhouse/*.whl
  deploy:
    runs-on: ubuntu-latest
    needs: [build-linux-wheels, build-macos-m1-wheel]
    steps:
      - name: start deploying
        uses: actions/checkout@v2
      - name: load py37 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.7.16 3.7 wheel
      - name: load py38 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.8.16 3.8 wheel
      - name: load py39 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.9.16 3.9 wheel
      - name: load py310 wheel
        uses: actions/download-artifact@v2
        with: 
          name: 3.10.10 3.10 wheel
      - name: load mac m1 wheel
        uses: actions/download-artifact@v2
        with:
          name: macos m1 wheel
      - name: move wheel
        run: | 
         mkdir dist
         mv *.whl dist/
         ls
         ls dist
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          pip install twine
          pip install pexpect
          python -m twine upload dist/*-manylinux*.whl