name: Publish Python distributions to PyPI
on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  push:
    branches:
      - fix/cd
jobs:
  deployment:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Start Env
        uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
        with:
          python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311'
          build-requirements: 'maturin'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install twine
          pip install pexpect
          pip install maturin
          pip install build --upgrade
      - name: Build
        run: |
          python -m build
          cd dist
          ls
          cd ..
      - name: Deploy to pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          twine upload dist/*-manylinux*.whl --verbose