name: Build and deploy to PyPI
on:
  push:
    branches:
      - fix/cd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Twine
        run: |
          pip install twine
          pip install pexpect
      - name: Build and upload manylinux wheel
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.7.16 3.7
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.8.16 3.8
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.9.16 3.9
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash \
            /io/build-wheels.sh 3.10.10 3.10
          python -m twine upload dist/wheelhouse/*-manylinux*.whl
      - name: Download & Test
        run: |
          python --version
          pip install jskiner
          pip freeze | grep jskiner
          cd examples
          ./test.sh