name: Build manylinux wheel
on:
  push:
    branches:
      - fix/cd
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        # Add other dependencies required by your package
        # For example, if you use numpy:
        # numpy-version: [1.18, 1.19, 1.20]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        # Add other dependencies required by your package
        # For example, if you use numpy:
        # pip install numpy==${{ matrix.numpy-version }}
    - name: Build manylinux wheel
      run: |
        docker run --rm -v $PWD:/io quay.io/pypa/manylinux2014_x86_64 /io/.github/scripts/build_wheel.sh