name: Build manylinux wheel
on:
  push:
    branches:
      - fix/cd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run image
      run: |
      docker run --rm -v $PWD:/io quay.io/pypa/manylinux2014_x86_64
    