name: Build and deploy to PyPI
on:
  push:
    branches:
      - fix/cd
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Rust and Maturin
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          pip install maturin
      - name: Install depdencies:
        run: | 
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install twine
          python -m pip install pexpect
          python -m pip install maturin
          python -m pip install build --upgrade
      - name: Build and upload manylinux wheel
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          ls
          docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash /io/build-wheels.sh
          python -m twine upload dist/*-manylinux*.whl